---
title: "qbild_update"
author: "Ayush Agarwal"
date: "12/08/2020"
output: pdf_document
---

## How to get Qbild?  

* Download the qbldcpp folder from the **[GitHub repo](https://github.com/ayushmclaren/gsoc_qbld)**,  
* Run the following commands :-  
  * R CMD build qbild
  * R CMD install qbildcpp_1.0.tar.gz  
  
After finishing the steps:  

```{r,message=FALSE}
library(qbild)
library(knitr)

set.seed(10)

##############
## Loading and manipulation of the data set
##############

data <- readRDS("~/airpollution.rda") #contains factor variables as well

nsim = 5000
p = 0.25

##with intercept
time_a = Sys.time()
out <- model.qbld(data, id = "id", fixed_formula = wheeze~age+I(age^2)+smoking+counts,
                  random_formula = ~counts , nsim, p = 0.25, summarize = TRUE, 
                  verbose = FALSE)  #intercept true for both, added manipulation of symbols
time_b = Sys.time() 
paste0("Time elapsed = ",round(time_b-time_a,2)," sec")

plot(out)
```

```{r}
##with intercept
time_a = Sys.time()
out2 <- model.qbld(data, id = "id", fixed_formula = wheeze~age+smoking+counts-1,
              random_formula = ~-. , nsim, p = 0.25, summarize = TRUE, method="Unblock",
                  verbose = FALSE)  #intercept true foronly random
time_b = Sys.time() 
paste0("Time elapsed = ",round(time_b-time_a,2)," sec")

plot(out2)
```