---
title: "QBLD - GSoC 2020"
author: "Ayush Agarwal"
date: "24/07/2020"
header-includes:
  - \usepackage{longtable}
  - \usepackage{setspace}\onehalfspacing
  - \usepackage{amsmath}
fontsize: 12pt
output: 
  pdf_document:
    latex_engine: xelatex
---

## Quantile Regression and the Asymmetric Lalplace Distribution

**The Model**

The QBLD model can be conveniently expressed in the latent variable formulation (Albert & Chib, 1993) as follows:

\begin{equation}\label{eq1}
\begin{gathered}
z_{it}=x_{it}^{'}\beta+s_{it}^{'}\alpha_{i}+\epsilon_{it},\hspace{30pt}\forall i = 1,...,n; t = 1,...,T_{i}\\y_{it}=\begin{cases}\text{1}  &\quad {if\,z_{it}> 0} \\\text{0} &\quad\text{otherwise,}\\\end{cases}\end{gathered}\end{equation}  
$y_{it} =$ response variable $y$ at $t^{th}$ time period for the $i^{th}$ individual,  
$z_{it} =$ unobserved latent variable $z$ at $t^{th}$ time period for the $i^{th}$ individual,  
$x_{it}^{'}$ = $1 × k$ vector of fixed-effects covariates,   
$\beta$ = $k × 1$ vector of fixed-effects parameters,   
$s_{it}^{'}$ = $1 × l$ vector of covariates that have individual-specific effects,   
$\alpha_{i}$ = $l × 1$ vector of individual-specific parameters, and   
$\epsilon_{it}$ = the error term $\overset{\mathrm{iid}}{\sim} AL(0, 1, p)$. (AL is Asymmteric Laplace Distribution.)     


**ALD Mixture**  

While working directly with the AL density is an option, the resulting posterior will not yield the full set of tractable conditional distributions necessary for a Gibbs sampler. The mixture representation gives access to the appealing properties of the normal distribution. Thus, we utilize the normal-exponential mixture representation of the AL distribution, presented in Kozumi and Kobayashi (2011) :

\begin{equation}\label{eq2}
\epsilon_{it} = w_{it}\theta + \tau\sqrt{w_{it}}u_{it} \hspace{30pt} \forall i = 1,...,n;  t = 1,...,T_{i}\,
\end{equation}
$u_{it} \sim N(0,1)$, is mutually inependent of $w_{it} \sim \exp(1)$,  
$\theta = \frac{1-2p}{p(1-p)}$, and $\tau = \sqrt{\frac{2}{p(1-p)}}$.  


**Model with Priors**

Longitudinal data models often involve a moderately large amount of data, so it is important to take advantage of any opportunity to reduce the computational burden. One such trick is to stack the model for each individual $i$ (Hendricks, Koenker, & Poirier, 1979).   

We define, $z_{i} = (z_{i1},...,z_{iT_{i}})^{'}$, $X_{i} = (x_{i1}^{'},...,x_{iT_{i}}^{'})^{'}$, $S_{i} = (s_{i1}^{'},...,s_{iT_{i}}^{'})^{'}$, $w_{i} = (w_{i1},...,w_{iT_{i}})^{'}$, $D_{\tau\sqrt{w_{i}}} =  diag(\tau\sqrt{w_{i1}},...,\tau\sqrt{w_{iT_{i}}})^{'}$, and $u_{i} = (u_{i1},...,u_{iT_{i}})^{'}$.  

Building on Eqs. (\ref{eq1}) and (\ref{eq2}),  

\begin{equation}\label{eq3}
\begin{gathered}
z_{i} = X_{i}\beta+S_{i}\alpha_{i}+w_{i}\theta + D_{\tau\sqrt{w_{i}}}u_{i},\\y_{it}=\begin{cases}\text{1}  &\quad {if\,z_{it}> 0} \\\text{0} &\quad\text{otherwise,}\\\end{cases}\\\alpha_{i}|\varphi^{2}\sim N_{l}(0,\varphi^{2}I_{l}), w_{it} \sim \exp(1), u_{it} \sim N(0,1)\\\beta\sim N_{k}(\beta_{0},B_{0}), \varphi^{2}\sim IG(c1/2, d1/2)\end{gathered}\end{equation}  


## Algorithm

### Blocked Sampling

* Sample $(\beta,z_{i})$ in one block. These are sampled in following two substeps. 

  (1) Sample $\beta$
  \begin{equation}\begin{gathered}\label{eq4}\\\beta|z,w,\varphi^{2}\sim N(\tilde{\beta},\tilde{B}),\\where,\hspace{10pt}\tilde{B}^{-1}=(\sum_{i=1}^{n}X_{i}^{'}\Omega_{i}^{-1}X_{i}+B_{0}^{-1}),\\\tilde{\beta}=\tilde{B}(\sum_{i=1}^{n}X_{i}^{'}\Omega_{i}^{-1}(z_{i}-w_{i}\theta)+B_{0}^{-1}\beta_{0}),\\\Omega_{i}=(\varphi^{2}S_{i}S_{i}^{'}+D^{2}_{\tau\sqrt{w_{i}}}).\end{gathered}\end{equation}  
  
  (2) Sample the vector $z_{i}|y_{i},\beta,w_{i},\varphi^{2}\sim TMVN_{B_{i}}(X_{i}\beta+w_{i}\theta,\Omega_{i})$ for all $i=1,...,n$, where $B_{i}=(B_{i1}*B_{i2}*...*B_{iT_{i}})$ and $B_{it}$ are interval $(0,\infty)$ if $y_{it}=1$, and the interval $(-\infty,0]$ if $y_{it}=0$. This is done by sampling $z_{i}$ at the $j^{th}$ pass of the MCMC iteration using a series of conditional posteriors:  
  
  \begin{equation}\begin{gathered}\label{eq5}z_{it}^{j}|z_{i1}^{j},...z_{i(t-1)}^{j},z_{i(t+1)}^{j-1},...,z_{iT_{i}}^{j-1}\sim TN_{B_{i}}(\mu_{t|-t},\Sigma_{t|-t}),\hspace{20pt}t=1,...,T_{i}.\\where,\hspace{10pt}\mu_{t|-t}=x_{it}^{'}\beta+w_{it}\theta + \Sigma_{t,-t}\Sigma_{-t,-t}^{-1}(z_{i,-t}^{j}-(X_{i}\beta+w_{i}\theta)_{-t}),\\\Sigma_{t|-t}=\Sigma_{t,t}-\Sigma_{t,-t}\Sigma_{-t,-t}^{-1}\Sigma_{-t,t},\end{gathered}\end{equation}  
  
  where $z_{i,-t}^{j}=(z_{i1}^{j},...z_{i(t-1)}^{j},z_{i(t+1)}^{j-1},...,z_{iT_{i}}^{j-1})$, $(X_{i}\beta+w_{i}\theta)_{-t}$ is column vector with $t^{th}$ element removed, $\Sigma_{t,t},\Sigma_{t,-t},\Sigma_{-t,-t}$ are $(t,t)^{th}$ element, $t^{th}$ row with $t^{th}$ element removed, and $t^{th}$ row and column removed respectively.  
  
* Sample $\alpha$

\begin{equation}\begin{gathered}\label{eq6}\alpha_{i}|z,\beta,w,\varphi^{2}\sim N(\tilde{a},\tilde{A}),\hspace{10pt} \forall i = 1,...,n\\where,\hspace{10pt}\tilde{A^{-1}}=(S_{i}^{'}D^{-2}_{\tau\sqrt{w_{i}}}S_{i}+\frac{1}{\varphi^{2}}I_{l}),\\\tilde{a}=\tilde{A}(S_{i}^{'}D^{-2}_{\tau\sqrt{w_{i}}}(z_{i}-X_{i}\beta-w_{i}\theta)).\end{gathered}\end{equation}  

* Sample $w$

\begin{equation}\begin{gathered}\label{eq7}w_{it}|z_{it},\beta,\alpha_{i}\sim GIG(0.5,\tilde{\lambda_{it}},\tilde{\eta})\hspace{10pt} \forall i = 1,...,n;  t = 1,...,T_{i},\\where,\hspace{10pt} \tilde{\lambda_{it}}=(\frac{z_{it}-x_{it}^{'}\beta-s_{it}^{'}\alpha_{i}}{\tau})^{2}\\\tilde{\eta}=(\frac{\theta^{2}}{\tau^{2}}+2).\end{gathered}\end{equation}  

* Sample $\varphi^{2}$

\begin{equation}\begin{gathered}\label{eq8}\varphi^{2}|\alpha\sim IG(\tilde{c_{1}}/2,\tilde{d_{1}}/2),\\where, \hspace{10pt}\tilde{c_{1}}=(nl+c_{1}),\\\tilde{d_{1}}=(\sum_{i=1}^{n}\alpha_{i}^{'}\alpha_{i} + d_{1}).\end{gathered}\end{equation}.  


### Unblocked Sampling  

* Sample $\beta$  

\begin{equation}\begin{gathered}\label{eq9}\\\beta|z,w,\varphi^{2}\sim N(\tilde{\beta},\tilde{B}),\\where,\hspace{10pt}\tilde{B}^{-1}=(\sum_{i=1}^{n}X_{i}^{'}\Psi_{i}^{-1}X_{i}+B_{0}^{-1}),\\\tilde{\beta}=\tilde{B}(\sum_{i=1}^{n}X_{i}^{'}\Psi_{i}^{-1}(z_{i}-w_{i}\theta-S_{i}\alpha_{i})+B_{0}^{-1}\beta_{0}),\\\Psi_{i}=D^{2}_{\tau\sqrt{w_{i}}}.\end{gathered}\end{equation}  

* Sample $\alpha$ as in (\ref{eq6}).  

* Sample $w$ as in (\ref{eq7}).  

* Sample $\varphi^{2}$ as in (\ref{eq8}).

* Sample $z|y,\alpha,w \hspace{5pt}\forall i = 1,...,n;  t = 1,...,T_{i}$, from univariate truncated normal as: 

\begin{equation}\label{eq10}z_{it}|y,\beta,w=\begin{cases}{TN_{(-\infty,0]}(x_{it}^{'}\beta+s_{it}^{'}\alpha_{i}+w_{it}\theta,\tau^{2}w_{it})}&\quad{if\,y_{it}=0}\\{TN_{(0,\infty)}(x_{it}^{'}\beta+s_{it}^{'}\alpha_{i}+w_{it}\theta,\tau^{2}w_{it})}&\quad {if\,y_{it}=1}\\\end{cases}\end{equation}.


## How to get Qbild?  

* Download the qbldcpp folder from the **[GitHub repo](https://github.com/ayushmclaren/gsoc_qbld)**,  
* Run the following commands :-  
  * R CMD build qbild
  * R CMD install qbildcpp_1.0.tar.gz  
  
After finishing the steps:  

```{r,message=FALSE}
library(qbild)
library(knitr)

set.seed(10)

##############
## Loading and manipulation of the data set
##############

data <- readRDS("~/airpollution.rda") #contains factor variables as well

nsim = 5000
p = 0.25

##with intercept
time_a = Sys.time()
out <- model.qbld(data, id = "id", fixed_formula = wheeze~age+I(age^2)+smoking+counts,
                  random_formula = ~counts , nsim, p = 0.25, summarize = TRUE, 
                  verbose = FALSE)  #intercept true for both, added manipulation of symbols
time_b = Sys.time() 
paste0("Time elapsed = ",round(time_b-time_a,2)," sec")

plot(out)
```










