# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgig <- function(x, a, b, p, log_density) {
    .Call(`_FinalBlock_dgig`, x, a, b, p, log_density)
}

rgig <- function(n, lambda, a, b) {
    .Call(`_FinalBlock_rgig`, n, lambda, a, b)
}

