# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib GIGpack
#' @importFrom Rcpp sourceCpp
NULL

dgig <- function(x, a, b, p, log_density) {
    .Call('_GIGpack_dgig', PACKAGE = 'GIGpack', x, a, b, p, log_density)
}

#' @useDynLib GIGpack
#' @importFrom Rcpp sourceCpp
NULL

rgig <- function(n, lambda, a, b) {
    .Call('_GIGpack_rgig', PACKAGE = 'GIGpack', n, lambda, a, b)
}

