// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dgig
std::vector<double> dgig(std::vector<double> x, double a, double b, double p, bool log_density);
RcppExport SEXP _GIGpack_dgig(SEXP xSEXP, SEXP aSEXP, SEXP bSEXP, SEXP pSEXP, SEXP log_densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type log_density(log_densitySEXP);
    rcpp_result_gen = Rcpp::wrap(dgig(x, a, b, p, log_density));
    return rcpp_result_gen;
END_RCPP
}
// rgig
arma::vec rgig(double n, double lambda, double a, double b);
RcppExport SEXP _GIGpack_rgig(SEXP nSEXP, SEXP lambdaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rgig(n, lambda, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GIGpack_dgig", (DL_FUNC) &_GIGpack_dgig, 5},
    {"_GIGpack_rgig", (DL_FUNC) &_GIGpack_rgig, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_GIGpack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
