# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib qbild
#' @importFrom Rcpp sourceCpp
NULL

qbldf <- function(nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose) {
    .Call(`_qbild_qbldf`, nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose)
}

#' @useDynLib qbild
#' @importFrom Rcpp sourceCpp
NULL

datagen <- function(n, m, p) {
    .Call(`_qbild_datagen`, n, m, p)
}

#' @useDynLib qbild
#' @importFrom Rcpp sourceCpp
NULL

raldmix <- function(n, mu, sigma, p) {
    .Call(`_qbild_raldmix`, n, mu, sigma, p)
}

#' @useDynLib qbild
#' @importFrom Rcpp sourceCpp
NULL

rgig <- function(n, lambda, a, b) {
    .Call(`_qbild_rgig`, n, lambda, a, b)
}

#' @useDynLib qbild
#' @importFrom Rcpp sourceCpp
NULL

qbldunblock <- function(nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose) {
    .Call(`_qbild_qbldunblock`, nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose)
}

