# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib qbld
#' @importFrom Rcpp sourceCpp
NULL

qbldf <- function(nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose) {
    .Call(`_qbld_qbldf`, nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose)
}

#' @useDynLib qbld
#' @importFrom Rcpp sourceCpp
NULL

dgig <- function(x, a, b, p, log_density) {
    .Call(`_qbld_dgig`, x, a, b, p, log_density)
}

#' @useDynLib qbld
#' @importFrom Rcpp sourceCpp
NULL

raldmix <- function(n, mu, sigma, p) {
    .Call(`_qbld_raldmix`, n, mu, sigma, p)
}

#' @useDynLib qbld
#' @importFrom Rcpp sourceCpp
NULL

rgig <- function(n, lambda, a, b) {
    .Call(`_qbld_rgig`, n, lambda, a, b)
}

#' @useDynLib qbld
#' @importFrom Rcpp sourceCpp
NULL

qbldunblock <- function(nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose) {
    .Call(`_qbld_qbldunblock`, nsim, p, y, datax, datas, b0, B0, c1, d1, m, n, k, l, verbose)
}

