# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib FinalBlock, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL
#' @rdname FinalBlock
#' @export


dgig <- function(x, a, b, p, log_density) {
    .Call(`_FinalBlock_dgig`, x, a, b, p, log_density)
}

#' @useDynLib FinalBlock, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL
#' @rdname FinalBlock
#' @export

rgig <- function(P, a, b, n) {
    .Call(`_FinalBlock_rgig`, P, a, b, n)
}

