# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib qbldcpp
#' @importFrom Rcpp sourceCpp
NULL

qbldf <- function(nsim, p, y, datax, datas, x_intercept, s_intercept, b0, B0, c1, d1, burnin) {
    .Call(`_qbldcpp_qbldf`, nsim, p, y, datax, datas, x_intercept, s_intercept, b0, B0, c1, d1, burnin)
}

#' @useDynLib qbldcpp
#' @importFrom Rcpp sourceCpp
NULL

datagen <- function(n, m, p) {
    .Call(`_qbldcpp_datagen`, n, m, p)
}

#' @useDynLib qbldcpp
#' @importFrom Rcpp sourceCpp
NULL

raldmix <- function(n, mu, sigma, p) {
    .Call(`_qbldcpp_raldmix`, n, mu, sigma, p)
}

#' @useDynLib qbldcpp
#' @importFrom Rcpp sourceCpp
NULL

rgig <- function(n, lambda, a, b) {
    .Call(`_qbldcpp_rgig`, n, lambda, a, b)
}

#' @useDynLib qbldcpp
#' @importFrom Rcpp sourceCpp
NULL

qbldunblock <- function(nsim, p, y, datax, datas, x_intercept, s_intercept, b0, B0, c1, d1, burnin) {
    .Call(`_qbldcpp_qbldunblock`, nsim, p, y, datax, datas, x_intercept, s_intercept, b0, B0, c1, d1, burnin)
}

